--EXERCÍCIO 1
SELECT FIRST_NAME || ' ' || LAST_NAME AS "FULL_NAME", JOB_TITLE 
    FROM EMPLOYEES
    NATURAL JOIN JOBS;
    
--EXERCÍCIO 2
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "FULL_NAME"
    FROM DEPARTMENTS d
    LEFT OUTER JOIN EMPLOYEES e ON d.MANAGER_ID = e.EMPLOYEE_ID;
    
--EXERCÍCIO 3
SELECT FIRST_NAME, DEPARTMENT_NAME 
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    WHERE DEPARTMENT_NAME = 'Sales';
    
--EXERCÍCIO 4
SELECT FIRST_NAME 
    FROM EMPLOYEES e
    WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
    
--EXERCÍCIO 5
SELECT FIRST_NAME, e.JOB_ID, j.JOB_TITLE
    FROM EMPLOYEES e
    INNER JOIN JOBS j ON e.JOB_ID = j.JOB_ID
    WHERE e.JOB_ID = (SELECT JOB_ID FROM EMPLOYEES 
                        WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King');
                        
--EXERCÍCIO 6
SELECT FIRST_NAME 
    FROM EMPLOYEES e
    WHERE e.HIRE_DATE < (SELECT HIRE_DATE FROM EMPLOYEES e
                         INNER JOIN DEPARTMENTS d ON e.EMPLOYEE_ID = d.MANAGER_ID
                         WHERE DEPARTMENT_NAME = 'Sales');

--EXERCÍCIO 7
SELECT DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID) AS "Funcionários" 
    FROM DEPARTMENTS d
        INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY (DEPARTMENT_NAME)
    HAVING
        COUNT(e.EMPLOYEE_ID) > 5;

--EXERCÍCIO 8
SELECT DEPARTMENT_NAME, SUM(e.SALARY) AS "Salário total"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY (DEPARTMENT_NAME);
    
--EXERCÍCIO 9
SELECT DEPARTMENT_NAME, AVG(e.SALARY) AS "Média salarial"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY ROLLUP(d.DEPARTMENT_NAME);
    
--EXERCÍCIO 10

 