--EXERCÍCIO 1
SELECT FIRST_NAME || ' ' || LAST_NAME AS "FULL_NAME", JOB_TITLE 
    FROM EMPLOYEES
    NATURAL JOIN JOBS;
    
--EXERCÍCIO 2
SELECT DEPARTMENT_NAME, FIRST_NAME || ' ' || LAST_NAME AS "FULL_NAME"
    FROM DEPARTMENTS d
    LEFT OUTER JOIN EMPLOYEES e ON d.MANAGER_ID = e.EMPLOYEE_ID;
    
--EXERCÍCIO 3
SELECT FIRST_NAME, DEPARTMENT_NAME 
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    WHERE DEPARTMENT_NAME = 'Sales';
    
--EXERCÍCIO 4
SELECT FIRST_NAME 
    FROM EMPLOYEES e
    WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
    
--EXERCÍCIO 5
SELECT FIRST_NAME, e.JOB_ID, j.JOB_TITLE
    FROM EMPLOYEES e
    INNER JOIN JOBS j ON e.JOB_ID = j.JOB_ID
    WHERE e.JOB_ID = (SELECT JOB_ID FROM EMPLOYEES 
                        WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King');
                        
--EXERCÍCIO 6
SELECT FIRST_NAME 
    FROM EMPLOYEES e
    WHERE e.HIRE_DATE < (SELECT HIRE_DATE FROM EMPLOYEES e
                         INNER JOIN DEPARTMENTS d ON e.EMPLOYEE_ID = d.MANAGER_ID
                         WHERE DEPARTMENT_NAME = 'Sales');

--EXERCÍCIO 7
SELECT DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID) AS "Funcionários" 
    FROM DEPARTMENTS d
        INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY (DEPARTMENT_NAME)
    HAVING
        COUNT(e.EMPLOYEE_ID) > 5;

--EXERCÍCIO 8
SELECT DEPARTMENT_NAME, SUM(e.SALARY) AS "Salário total"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY (DEPARTMENT_NAME);
    
--EXERCÍCIO 9
SELECT DEPARTMENT_NAME, AVG(e.SALARY) AS "Média salarial"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY ROLLUP(d.DEPARTMENT_NAME);
    
--EXERCÍCIO 10
SELECT DEPARTMENT_NAME, JOB_ID, SUM(e.SALARY) AS "SALARIO TOTAL"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY ROLLUP(DEPARTMENT_NAME, JOB_ID);
    
--EXERCÍCIO 11
SELECT DEPARTMENT_NAME, JOB_ID, SUM(e.SALARY) AS "SALARIO TOTAL"
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    GROUP BY GROUPING SETS((DEPARTMENT_NAME, JOB_ID), DEPARTMENT_NAME, JOB_ID);

--EXERCÍCIO 12
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS "NOME_COMPLETO", e.JOB_ID, g.FIRST_NAME || ' ' || g.LAST_NAME AS "GERENTE"
    FROM EMPLOYEES e
    INNER JOIN EMPLOYEES g 
        ON e.MANAGER_ID = g.EMPLOYEE_ID
    NATURAL JOIN JOBS j;
    
--EXERCÍCIO 13
SELECT DISTINCT DEPARTMENT_NAME 
    FROM DEPARTMENTS d
    INNER JOIN EMPLOYEES e
        USING(DEPARTMENT_ID)
    WHERE EXISTS (SELECT * FROM EMPLOYEES WHERE EMPLOYEES.JOB_ID = 'SA_REP');

--EXERCÍCIO 14
SELECT e.FIRST_NAME, e.SALARY AS "SALARIO FUNCIONARIO", g.SALARY AS "SALARIO GERENTE"   
    FROM EMPLOYEES e 
    INNER JOIN EMPLOYEES g
        ON e.MANAGER_ID = g.EMPLOYEE_ID
    WHERE e.SALARY > g.SALARY;

--EXERCÍCIO 15
SELECT FIRST_NAME || ' ' || LAST_NAME AS "NOME_COMPLETO"
    FROM EMPLOYEES e
    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                                FROM DEPARTMENTS d
                                INNER JOIN EMPLOYEES e
                                    USING(DEPARTMENT_ID)
                                 WHERE e.SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES));

--EXERCÍCIO 16 ****
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS "NOME_COMPLETO"
    FROM EMPLOYEES e
    INNER JOIN EMPLOYEES g
        USING(HIRE_DATE);

--EXERCÍCIO 17
SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) 
    FROM EMPLOYEES e
    RIGHT JOIN DEPARTMENTS d
        USING(DEPARTMENT_ID)
    GROUP BY(DEPARTMENT_NAME);
    















 