--Exercício 1
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, DEPARTMENT_ID FROM EMPLOYEES
WHERE LAST_NAME <> 'Zlotkey' and DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES
WHERE LAST_NAME = 'Zlotkey');

--Exercício 2
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME = 'Davies');

--Exercício 3
SELECT LAST_NAME FROM EMPLOYEES e
WHERE EXISTS(SELECT * FROM DEPARTMENTS WHERE e.EMPLOYEE_ID = MANAGER_ID);

--Exercício 4

--sem join
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(SELECT EMPLOYEE_ID FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE d.DEPARTMENT_NAME NOT LIKE '%Sales%');

--com join
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE DEPARTMENTS.DEPARTMENT_NAME NOT LIKE '%Sales%';

--checando quantidade
SELECT COUNT(*) AS NUMERO FROM EMPLOYEES e 
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE d.DEPARTMENT_NAME NOT LIKE '%Sales%';

--Exercício 5
SELECT LAST_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY < SOME (SELECT SALARY FROM EMPLOYEES 
WHERE JOB_ID = 'ST_MAN');

--checando maior salário
SELECT MAX(SALARY) FROM EMPLOYEES 
WHERE JOB_ID = 'ST_MAN';

--Exercício 6
SELECT LAST_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY > ALL(SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50);

--checando maior salário
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

--Exercício 7
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES 
WHERE LAST_NAME = 'Zlotkey') and JOB_ID = (SELECT JOB_ID FROM EMPLOYEES
WHERE LAST_NAME = 'Zlotkey');

--Exercício 8
SELECT COUNTRY_ID FROM COUNTRIES
JOIN LOCATIONS ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
JOIN DEPARTMENTS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;

