SELECT DEPARTMENT_ID, JOB_ID, COUNTRY_NAME, REGION_NAME, SUM(SALARY) 
    FROM EMPLOYEES
        JOIN DEPARTMENTS USING(DEPARTMENT_ID)
        JOIN LOCATIONS USING (LOCATION_ID)
        JOIN COUNTRIES USING (COUNTRY_ID)
        JOIN REGIONS USING (REGION_ID)
    WHERE DEPARTMENT_ID < 50
    GROUP BY CUBE(DEPARTMENT_ID, JOB_ID, COUNTRY_NAME, REGION_NAME);


SELECT DEPARTMENT_ID, JOB_ID, COUNTRY_NAME, REGION_NAME, SUM(SALARY) 
    FROM EMPLOYEES
        JOIN DEPARTMENTS USING(DEPARTMENT_ID)
        JOIN LOCATIONS USING (LOCATION_ID)
        JOIN COUNTRIES USING (COUNTRY_ID)
        JOIN REGIONS USING (REGION_ID)
    WHERE DEPARTMENT_ID < 50
    GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID, COUNTRY_NAME, REGION_NAME);
    

SELECT department_id, job_id, manager_id, SUM(salary)
    FROM employees
    WHERE department_id < 50
    GROUP BY GROUPING SETS
        ((job_id, manager_id),(department_id, job_id),
        (department_id, manager_id));   