-- Exercício 1
SELECT LAST_NAME, SALARY, JOB_TITLE FROM EMPLOYEES e 
NATURAL JOIN JOBS j
WHERE j.JOB_TITLE = 'Sales Representative' OR j.JOB_TITLE = 'Stock Clerk';

-- Exercício 2
SELECT COUNTRY_NAME, REGION_NAME FROM COUNTRIES c
INNER JOIN REGIONS r
USING(REGION_ID);

-- Exercício 3
SELECT DEPARTMENT_NAME, LAST_NAME, SALARY FROM DEPARTMENTS d
INNER JOIN EMPLOYEES e 
ON e.EMPLOYEE_ID = d.MANAGER_ID
WHERE e.SALARY < 10000;

-- Exercício 4
SELECT FIRST_NAME, LAST_NAME, CITY FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d
    USING (DEPARTMENT_ID)
    INNER JOIN LOCATIONS l
    USING(LOCATION_ID)
WHERE l.CITY LIKE 'S%';

-- Exercício 5
SELECT LAST_NAME, DEPARTMENT_NAME, REGION_NAME FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d
    USING(DEPARTMENT_ID)
    INNER JOIN LOCATIONS l
    USING(LOCATION_ID)
    INNER JOIN COUNTRIES c
    USING(COUNTRY_ID)
    INNER JOIN REGIONS r
    USING(REGION_ID)
WHERE r.REGION_NAME = 'Europe';

-- Exercício 6
SELECT e.LAST_NAME, e.JOB_ID, g.LAST_NAME, g.JOB_ID FROM EMPLOYEES e
    INNER JOIN EMPLOYEES g
    ON e.MANAGER_ID = g.EMPLOYEE_ID;
    
-- Exercício 7
SELECT DEPARTMENT_NAME, LAST_NAME FROM DEPARTMENTS d
    LEFT OUTER JOIN EMPLOYEES e
    ON e.EMPLOYEE_ID = d.MANAGER_ID;
    
-- Exercício 8
SELECT LAST_NAME, e.JOB_ID, START_DATE, END_DATE FROM EMPLOYEES e
    LEFT OUTER JOIN JOB_HISTORY jh
    USING(EMPLOYEE_ID);
    